micronaut:

datasources:
  default:
    url: jdbc:h2:mem:test-db
    driverClassName: org.h2.Driver
    username: teste
    password: teste
    schema-generate: CREATE_DROP
    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true
        format_sql: false

flyway:
  datasources:
    default:
      enabled: false
