version: "3.9"
services:
  db-postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /opt/postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
  transaction-manager:
    build: .
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db-postgres
    env_file:
      - .env
