-- region DOCUMENT_TYPE
CREATE TABLE DOCUMENT_TYPE (
    IDT_DOCUMENT_TYPE UUID DEFAULT gen_random_uuid() NOT NULL,
    DAT_CREATED       TIMESTAMP WITH TIME ZONE       NOT NULL,
    DAT_UPDATED       TIMESTAMP WITH TIME ZONE       NOT NULL,
    COD_DOCUMENT_TYPE NUMERIC(3)                     NOT NULL,
    DES_DOCUMENT_TYPE TEXT                           NOT NULL,

    CONSTRAINT IDT_DOCUMENT_TYPE_PK PRIMARY KEY (IDT_DOCUMENT_TYPE),
    CONSTRAINT DES_DOCUMENT_TYPE_LENGTH_CK CHECK (CHAR_LENGTH(DES_DOCUMENT_TYPE) <= 12),
    CONSTRAINT COD_DOCUMENT_TYPE_UQ UNIQUE (COD_DOCUMENT_TYPE)
);

CREATE INDEX IF NOT EXISTS DOCUMENT_TYPE_COD_DOCUMENT_TYPE_IX ON DOCUMENT_TYPE(COD_DOCUMENT_TYPE);
-- endregion

-- region CUSTOMER
CREATE TABLE CUSTOMER (
    IDT_CUSTOMER      UUID DEFAULT gen_random_uuid() NOT NULL,
    DAT_CREATED       TIMESTAMP WITH TIME ZONE       NOT NULL,
    DAT_UPDATED       TIMESTAMP WITH TIME ZONE       NOT NULL,
    NAM_CUSTOMER      TEXT                           NOT NULL,
    DAT_BIRTHDAY      DATE                           NOT NULL,
    NUM_DOCUMENT      TEXT                           NOT NULL,
    IDT_DOCUMENT_TYPE UUID                           NOT NULL,

    CONSTRAINT IDT_CUSTOMER_PK PRIMARY KEY (IDT_CUSTOMER),
    CONSTRAINT NAM_CUSTOMER_LENGTH_CK CHECK (CHAR_LENGTH(NAM_CUSTOMER) <= 64),
    CONSTRAINT NUM_DOCUMENT_LENGTH_CK CHECK (CHAR_LENGTH(NUM_DOCUMENT) <= 25),

    CONSTRAINT CUSTOMER_DOCUMENT_TYPE_FK FOREIGN KEY (IDT_DOCUMENT_TYPE) REFERENCES DOCUMENT_TYPE(IDT_DOCUMENT_TYPE)
);

CREATE INDEX IF NOT EXISTS CUSTOMER_IDT_DOCUMENT_TYPE_IX ON CUSTOMER(IDT_DOCUMENT_TYPE);
-- endregion

-- region ACCOUNT
CREATE TABLE ACCOUNT (
    IDT_ACCOUNT  UUID DEFAULT gen_random_uuid() NOT NULL,
    DAT_CREATED  TIMESTAMP WITH TIME ZONE       NOT NULL,
    DAT_UPDATED  TIMESTAMP WITH TIME ZONE       NOT NULL,
    NUM_ACCOUNT  TEXT                           NOT NULL,
    IDT_CUSTOMER UUID                           NOT NULL,

    CONSTRAINT IDT_ACCOUNT_PK PRIMARY KEY (IDT_ACCOUNT),
    CONSTRAINT NUM_ACCOUNT_LENGTH_CK CHECK (CHAR_LENGTH(NUM_ACCOUNT) <= 12),
    CONSTRAINT NUM_ACCOUNT_TYPE_UQ UNIQUE (NUM_ACCOUNT),

    CONSTRAINT ACCOUNT_CUSTOMER_FK FOREIGN KEY (IDT_CUSTOMER) REFERENCES CUSTOMER(IDT_CUSTOMER)
);

CREATE INDEX IF NOT EXISTS ACCOUNT_IDT_CUSTOMER_IX ON ACCOUNT(IDT_CUSTOMER);
-- endregion

-- region TRANSACTION_TYPE
CREATE TABLE TRANSACTION_TYPE (
    IDT_TRANSACTION_TYPE UUID DEFAULT gen_random_uuid() NOT NULL,
    DAT_CREATED          TIMESTAMP WITH TIME ZONE       NOT NULL,
    DAT_UPDATED          TIMESTAMP WITH TIME ZONE       NOT NULL,
    COD_TRANSACTION_TYPE NUMERIC(3)                     NOT NULL,
    DES_TRANSACTION_TYPE TEXT                           NOT NULL,
    IND_OPERATION        NUMERIC(2)                     NOT NULL,

    CONSTRAINT IDT_TRANSACTION_TYPE_PK PRIMARY KEY (IDT_TRANSACTION_TYPE),
    CONSTRAINT COD_TRANSACTION_TYPE_UQ UNIQUE (COD_TRANSACTION_TYPE),
    CONSTRAINT DES_TRANSACTION_TYPE_LENGTH_CK CHECK (CHAR_LENGTH(DES_TRANSACTION_TYPE) <= 12)
);

CREATE INDEX IF NOT EXISTS TRANSACTION_TYPE_COD_TRANSACTION_TYPE_IX ON TRANSACTION_TYPE(COD_TRANSACTION_TYPE);
-- endregion

-- region TRANSACTION_STATUS
CREATE TABLE TRANSACTION_STATUS (
    IDT_TRANSACTION_STATUS UUID DEFAULT gen_random_uuid() NOT NULL,
    DAT_CREATED            TIMESTAMP WITH TIME ZONE       NOT NULL,
    DAT_UPDATED            TIMESTAMP WITH TIME ZONE       NOT NULL,
    COD_TRANSACTION_STATUS NUMERIC(3)                     NOT NULL,
    DES_TRANSACTION_STATUS TEXT                           NOT NULL,

    CONSTRAINT IDT_TRANSACTION_STATUS_PK PRIMARY KEY (IDT_TRANSACTION_STATUS),
    CONSTRAINT COD_TRANSACTION_STATUS_UQ UNIQUE (COD_TRANSACTION_STATUS),
    CONSTRAINT DES_TRANSACTION_STATUS_LENGTH_CK CHECK (CHAR_LENGTH(DES_TRANSACTION_STATUS) <= 20)
);

CREATE INDEX IF NOT EXISTS TRANSACTION_TYPE_COD_TRANSACTION_STATUS_IX ON TRANSACTION_STATUS(COD_TRANSACTION_STATUS);
-- endregion

-- region TRANSACTION
CREATE TABLE TRANSACTION (
    IDT_TRANSACTION        UUID DEFAULT gen_random_uuid() NOT NULL,
    DAT_CREATED            TIMESTAMP WITH TIME ZONE       NOT NULL,
    DAT_UPDATED            TIMESTAMP WITH TIME ZONE       NOT NULL,
    DAT_EVENT              TIMESTAMP WITH TIME ZONE       NOT NULL,
    NUM_AMOUNT             NUMERIC                        NOT NULL,
    NUM_INSTALLMENTS       NUMERIC(2),
    IDT_TRANSACTION_TYPE   UUID                           NOT NULL,
    IDT_TRANSACTION_STATUS UUID                           NOT NULL,
    IDT_ACCOUNT            UUID                           NOT NULL,

    CONSTRAINT IDT_TRANSACTION_PK PRIMARY KEY (IDT_TRANSACTION),

    CONSTRAINT TRANSACTION_TRANSACTION_TYPE_FK FOREIGN KEY (IDT_TRANSACTION_TYPE) REFERENCES TRANSACTION_TYPE(IDT_TRANSACTION_TYPE),
    CONSTRAINT TRANSACTION_TRANSACTION_STATUS_FK FOREIGN KEY (IDT_TRANSACTION_STATUS) REFERENCES TRANSACTION_STATUS(IDT_TRANSACTION_STATUS),
    CONSTRAINT TRANSACTION_ACCOUNT_FK FOREIGN KEY (IDT_ACCOUNT) REFERENCES ACCOUNT(IDT_ACCOUNT)
);

CREATE INDEX IF NOT EXISTS TRANSACTION_IDT_TRANSACTION_TYPE_IX ON TRANSACTION(IDT_TRANSACTION_TYPE);
CREATE INDEX IF NOT EXISTS TRANSACTION_IDT_TRANSACTION_STATUS_IX ON TRANSACTION(IDT_TRANSACTION_STATUS);
CREATE INDEX IF NOT EXISTS TRANSACTION_IDT_ACCOUNT_IX ON TRANSACTION(IDT_ACCOUNT);
-- endregion
